### ISSUE TITLE
Glitched border on xubuntu

### ISSUE THREAD

**Issue by actionless** [actionless/oomox-gtk-theme#10]
_From @luismercado on July 1, 2016 0:16_

The color schemes are working fine, but the window decoration are glitched with a white border with some parts dotted others just plainly glitched. every expoerted theme behaves the same. I'm attaching a screenshot.

![screenshot_2016-06-30_17-07-23](https://cloud.githubusercontent.com/assets/20233577/16508279/584b3e16-3ee6-11e6-9ad7-63de2110fbab.png)

_Copied from original issue: actionless/oomox#41_

**Comment by actionless** [comment]
could you try it with reverting this commit https://github.com/actionless/oomox/commit/d56cbd8ea37ac1311b83269d8b99260d7a126607 ?

**Comment by actionless** [comment]
feel free to reopen

**Comment by actionless** [comment]
_From @FcoRTendero on October 9, 2017 16:45_

Hi, same issue here using xfce. I reverted d56cbd8 commit resizing those icons to 24x24 but it did not solve the problem

**Comment by actionless** [comment]
@FcoRTendero the think is what theme is moved to this repo, so reverting that commit in the main repo probably won't make any effect

**Comment by KUPOinyourWINDOW** [comment]
I'm able to reproduce this, but only with the ones created by oomox.
![screenshot_2017-11-19_16-06-51](https://user-images.githubusercontent.com/7698035/32992538-c1a5d6a4-cd43-11e7-9d09-d0ca8240c590.png)

**Comment by actionless** [comment]
@luismercado @FcoRTendero @KUPOinyourWINDOW 
fixed in https://github.com/actionless/oomox-gtk-theme/commit/73e1d7305a07d9e14db6adba36afac5a6fafaacf, please test
