### ISSUE TITLE
Better qt5 theme generation

### ISSUE THREAD

**Issue by actionless** [actionless/oomox-gtk-theme#22]
_From @angarod on February 21, 2018 17:54_

I'm using oomox with pywal for generating my colorscheme and i noticed qt5 theme based on gtk2 is not pretty. Some apps like virtualbox and nextcloud client are mixing white and black colours.

_Copied from original issue: actionless/oomox#124_

**Comment by actionless** [comment]
you can propose your fix here:
https://github.com/actionless/oomox-gtk-theme/blob/master/src/qt5ct_palette.conf

**Comment by actionless** [comment]
@angarod

i've revised your bug report

i think the problem what you're using GTK2 theme in Qt5 instead of qt5ct (recommended by Oomox)

**Comment by angarod** [comment]
what do you mean ? I'm using qt5ct for configuring my QT5 theme and i choosed gtk2 theme with wal colorscheme. Even if i choose another theme with wal colorscheme, i experience some white-grey lines in my keepassxc for example.

**Comment by actionless** [comment]
in `Style` dropbox instead of `gtk2` choose one of native Qt themes (recommended one is `Fusion`) and next in `Palette` choose `Custom` and choose `oomox-<YOUR_THEME_NAME>`

**Comment by actionless** [comment]
then it's quite evident what that color is just hardcoded in the app if the problem persists across GTK2/Fusion themes
