### ISSUE TITLE
Question - Should roundness be used in selected menu highlight?

### ISSUE THREAD

**Issue by smurphos** [actionless/oomox-gtk-theme#33]
Hi,

I think this is a matter of personal taste and it doesn't look great in all GTK menus (small right-click context menus with only a couple of entries can look a little 'off'). What do you think? I've got patches for GTK2, 3 and 3.20 that can be applied for this if you think it's worth including. Ignore the other differences between the screenshots - they are other personal tweaks I use (and may need to fix looking at this!)

![screenshot from 2018-03-17 05-33-24](https://user-images.githubusercontent.com/29017677/37552028-c44f1b0a-29a4-11e8-9e49-2df882a46fe8.png)
![screenshot from 2018-03-17 05-32-58](https://user-images.githubusercontent.com/29017677/37552029-c466d236-29a4-11e8-8ccf-16cdfbced0f7.png)
![screenshot from 2018-03-17 05-29-20](https://user-images.githubusercontent.com/29017677/37552030-c47c5516-29a4-11e8-9e65-be7dcabc5c95.png)
![screenshot from 2018-03-17 05-28-50](https://user-images.githubusercontent.com/29017677/37552031-c493c390-29a4-11e8-86b1-eab3e2c5fb26.png)

**Comment by actionless** [comment]
1) i don't think roundness working well in the menu highlight, mostly because menu itself doesn't have roundness
2) it's a good idea about borders, however i would prefer some much subtle mix of menu bg and fg colors
